package:
  format-version: "1.0.0"
  name: "vision"
  version: "v3.2.0"
  type: "api"
  status: "production"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.14.2"
    - name: "gfx"
      type: "package"
      version: "v3.16.0"
    - name: "usb"
      type: "package"
      version: "v3.15.0"
    - name: "bsp"
      type: "package"
      version: "v3.22.0"
    - name: "csp"
      type: "package"
      version: "v3.21.0"
