format_version: v1.0
configName: imx219_mipi_csi_isc_usb_msd
folderName: libcamera_usb_sama7g54_ek
frameworkPath: C:\harmony
processor: SAMA7G54D4G
projectName: libcamera_usb_sama7g54_ek
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMA7G5_DFP\1.2.178\atdf\SAMA7G54D4G.atdf
