format_version: v1.0
configName: isc_sama5d27_som1_ek1_tm5000
folderName: libcamera_sama5d27_som1_ek1
frameworkPath: C:\harmony
processor: ATSAMA5D27CD1G
projectName: libcamera_sama5d27_som1_ek1
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMA5D2_DFP\1.9.106\atdf\ATSAMA5D27CD1G.atdf
