package:
  format-version: "1.0.0"
  name: "vision"
  version: "3.0.0"
  type: "api"
  status: "production"

  dependencies:
    - name: "core"
      type: "package"
      version: "3.11.1"
    - name: "gfx"
      type: "package"
      version: "3.13.0"
